### ISSUE TITLE
Rule: Ensure pyproject.toml project.authors is set

### ISSUE THREAD

**Issue by josh** [josh/gh-audit#1]
Ensure `pypyproject.toml` sets `project.authors`. I *think* it might best to avoid setting the `email` field.

```toml
[project]
authors = [{name = "Joshua Peek"}]
```
