### ISSUE TITLE
Rule: Group Dependabot updates

### ISSUE THREAD

**Issue by josh** [josh/gh-audit#14]
Consider enforcing a Dependabot group rule like:

```yaml
groups:
  pip-dependencies:
    patterns:
      - '*'
```

if repo is getting too many update PRs.
