### ISSUE TITLE
Rule: Set Dependabot versioning strategy

### ISSUE THREAD

**Issue by josh** [josh/gh-audit#16]
I'm not sure which is best, but I don't want Dependabot always modifying the `pyproject.toml` file.

```yml
versioning-strategy: increase-if-necessary
versioning-strategy: widen
versioning-strategy: lockfile-only
```
