### ISSUE TITLE
Rule: Ensure pyproject.toml project.license is set

### ISSUE THREAD

**Issue by josh** [josh/gh-audit#2]
Ensure `pypyproject.toml` sets `project.license` as well as a `classifiers` for the license.

```toml
[project]
license = { file = "LICENSE" }
classifiers = [
    "License :: OSI Approved :: MIT License",
]
```
